
name: ci
on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Setup docker buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Run unit-tests
        run: ./src/run_tests.sh
      -
        name: Build example
        run: ./bin/tinylatex.sh ./example --main main.tex --latexmk-opt=-pdflua
