
name: ci
on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Setup docker buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Lint bash scripts
        run: |
          sudo apt-get update && sudo apt-get install -y shellcheck

          shellcheck bin/tinylatex
          find . -type f -name "*.sh" -print0 | xargs -0 shellcheck
      -
        name: Run unit-tests
        run: ./src/run_tests.sh
      -
        name: Build example
        run: ./bin/tinylatex ./example --main main.tex --latexmk-opt=-pdflua
